version: 2

updates:
  - package-ecosystem: npm
    target-branch: main
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    rebase-strategy: auto
    versioning-strategy: increase-if-necessary
    auto-merge: false
    commit-message:
      prefix: deps
      prefix-development: deps(dev)
    labels:
      - npm
      - dependencies
